name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '6 0 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: check *.channels.xml
        run: |
          npm run channels:lint
      - name: generate guidatv.sky.it
        run: npm run grab -- --channels=sites/guidatv.sky.it/guidatv.sky.it.channels.xml --output=guidatv.sky.it.guide.xml --maxConnections=3 --gzip
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.guide.xml,*.guide.xml.gz"
          allowUpdates: true
          generateReleaseNotes: false
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: false
          draft: false
          makeLatest: true
          tag: 1.0.0